packages:
  - 'frontend/apps/*'
  - 'frontend/packages/*'
  - 'backend/services/*'
  - 'backend/packages/*'

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  esbuild: true
  prisma: true
  sharp: true
