import type { RestaurantWithRelations } from './restaurants.repository';

export function toRestaurantResponse(restaurant: RestaurantWithRelations) {
  return {
    address: restaurant.address,
    b2cQrEnabled: restaurant.b2cQrEnabled,
    accountNumber: restaurant.accountNumber,
    atTableDining: restaurant.atTableDining,
    bankBranch: restaurant.bankBranch,
    bankName: restaurant.bankName,
    closingTime: restaurant.closingTime,
    coverImageUrl: restaurant.coverImageUrl,
    createdAt: restaurant.createdAt,
    deletedAt: restaurant.deletedAt,
    delivery: restaurant.delivery,
    email: restaurant.email,
    fssaiNumber: restaurant.fssaiNumber,
    fssaiNumbers: restaurant.fssaiNumber,
    gstNumber: restaurant.gstNumber,
    gstAddress: restaurant.gstAddress,
    homeDelivery: restaurant.homeDelivery,
    hospital: {
      city: restaurant.hospital.city,
      displayName: restaurant.hospital.displayName,
      hospitalCode: restaurant.hospital.hospitalCode,
      hospitalName: restaurant.hospital.hospitalName,
      id: restaurant.hospital.id,
      isActive: restaurant.hospital.isActive,
      locationCode: restaurant.hospital.hospitalCode,
      postalCode: restaurant.hospital.postalCode,
      state: restaurant.hospital.state,
      title: restaurant.hospital.hospitalName,
    },
    hospitalId: restaurant.hospitalId,
    id: restaurant.id,
    ifscCode: restaurant.ifscCode,
    inCarDining: restaurant.inCarDining,
    inRoomDining: restaurant.inRoomDiningEnabled,
    inRoomDiningEnabled: restaurant.inRoomDiningEnabled,
    inventory: restaurant.inventory,
    isAtTableDiningEnabled: restaurant.atTableDining,
    isDeliveryEnabled: restaurant.delivery,
    isHomeDeliveryEnabled: restaurant.homeDelivery,
    isInCarDiningEnabled: restaurant.inCarDining,
    isInRoomDiningEnabled: restaurant.inRoomDiningEnabled,
    isInventoryEnabled: restaurant.inventory,
    isOffline: restaurant.offline,
    isOnlineOrdersEnabled: restaurant.onlineOrderingEnabled,
    isOpen24x7: restaurant.open24x7,
    isPosOrdersEnabled: restaurant.posOrders,
    isRegisteredInGst: restaurant.isRegisteredInGst,
    isTakeawayEnabled: restaurant.takeaway,
    isVegOnly: restaurant.vegOnly,
    isActive: restaurant.isActive,
    kitchen: restaurant.kitchen
      ? {
          id: restaurant.kitchen.id,
          isActive: restaurant.kitchen.isActive,
          kitchenCode: restaurant.kitchen.kitchenCode,
          kitchenName: restaurant.kitchen.kitchenName,
        }
      : null,
    kitchenId: restaurant.kitchenId,
    kitchenIds: restaurant.restaurantKitchens.map((mapping) => mapping.kitchenId),
    kitchens: restaurant.restaurantKitchens.map((mapping) => ({
      id: mapping.kitchen.id,
      isActive: mapping.kitchen.isActive,
      kitchenCode: mapping.kitchen.kitchenCode,
      kitchenName: mapping.kitchen.kitchenName,
    })),
    legalName: restaurant.legalName,
    location: restaurant.location
      ? {
          id: restaurant.location.id,
          isActive: restaurant.location.isActive,
          locationName: restaurant.location.locationName,
        }
      : null,
    locationId: restaurant.locationId,
    mobile: restaurant.mobile,
    normalDiscountApplicable: restaurant.normalDiscountApplicable,
    offline: restaurant.offline,
    onlineOrders: restaurant.onlineOrderingEnabled,
    onlineOrderingEnabled: restaurant.onlineOrderingEnabled,
    openingTime: restaurant.openingTime,
    open24x7: restaurant.open24x7,
    panNumber: restaurant.panNumber,
    posOrders: restaurant.posOrders,
    qrUnitName: restaurant.qrUnitName,
    unitNameForQr: restaurant.qrUnitName,
    restaurantCode: restaurant.restaurantCode,
    restaurantName: restaurant.restaurantName,
    staffDiscountApplicable: restaurant.staffDiscountApplicable,
    store: restaurant.store
      ? {
          id: restaurant.store.id,
          isActive: restaurant.store.isActive,
          storeCode: restaurant.store.storeCode,
          storeName: restaurant.store.storeName,
        }
      : null,
    storeId: restaurant.storeId,
    bankNameBranch: restaurant.bankName,
    sodexoMid: restaurant.sodexoMid,
    sodexoTid: restaurant.sodexoTid,
    sunBu: restaurant.sunBu,
    sunT1: restaurant.sunT1,
    sunT2: restaurant.sunT2,
    takeaway: restaurant.takeaway,
    thumbnailUrl: restaurant.thumbnailUrl,
    updatedAt: restaurant.updatedAt,
    upiId: restaurant.upiId,
    vegOnly: restaurant.vegOnly,
  };
}
